name: Test

on:
  push:
    branches: [ master ]
  pull_request:
      types: [opened, synchronize, reopened]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: cfn-lint
      uses: scottbrenner/cfn-lint-action@master
      with:
        args: "**/*.yaml"
