name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
      types: [opened, synchronize, reopened]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: cfn-lint
      uses: scottbrenner/cfn-lint-action@v2

    - name: Print the Cloud Formation Linter Version & run Linter.
      run: |
        cfn-lint --version
        cfn-lint -t ./codepipeline/*.yaml
